server:
  port: 9999
  servlet:
    context-path: /kk
#配置mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.vdata.cloud.*.entity
  configuration:
    #    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  cache:
    type: caffeine
  datasource:
    #name: test
    url: jdbc:mysql://${MYSQL_HOST:192.168.0.200}:${MYSQL_PORT:3307}/nspdb?useUnicode=true&characterEncoding=UTF8&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
    #    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/zdaq?useUnicode=true&characterEncoding=UTF8&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid连接池的相关配置
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面SQL无法统计，wall用于防止sql注入
      filters: stat,wall
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null